services:
  mysql:
    volumes:
      - mysql-data:/var/lib/mysql:nocopy
  nginx:
    volumes:
      - laravel-repo:/data/www/app:nocopy
  php:
    volumes:
      - laravel-repo:/data/www/app:nocopy

volumes:
  mysql-data:
    external: true
  laravel-repo:
    external: true